### ISSUE TITLE
来，用SVG&CSS画一朵真实的云

### ISSUE THREAD

**Issue by lostvita** [qiudongwei/blog#12]
> 原文：[Drawing Realistic Clouds with SVG and CSS](https://css-tricks.com/drawing-realistic-clouds-with-svg-and-css/)

这是作者最终实现的效果：
![image](https://user-images.githubusercontent.com/26505680/60157235-dddaf300-9820-11e9-911e-283a46190509.png)
<font color="#A5A5A5">_在线查看效果：[cloud demo](https://codepen.io/beauhaus/pen/pmMaWV)_</font>

<br />

正文开始啦～

希腊神话讲述了一个关于宙斯创造云女神涅斐勒的故事。和其他希腊神话一样，这个故事极其怪异并且有点限制级。下面的表述则是一个比较简短且含蓄的版本（_限制级，非战斗人员请撤离_）。

<font color="5A78EA">**涅斐勒（云神）**</font>，据说是宙斯按照自己美丽妻子的形象创造的。传说有个凡人遇见了涅斐勒，一见钟情爱上了她并且在一起了，后来她们一起睡了一个觉，然后奇怪的事情发生了，一朵云生下了一个半人半马的小孩，传说这就半人马的祖先。

很不可思议对吗？就我个人而言，我搞不懂。但庆幸的是，浏览器中创建云的过程要简单得多，也没有那么不可描述。

![image](https://user-images.githubusercontent.com/26505680/60157260-eaf7e200-9820-11e9-943c-4ad0b3a9c1c7.png)
<font color="#A5A5A5">_这是@袁川画的云[demo](https://codepen.io/yuanchuan/pen/f70a1f9435dc90197b253b26b4d69d42)_</font>

最近，我发现开发者 _[@袁川](https://codepen.io/yuanchuan/)_ 已经用代码实现了仿真的云烟。对我来说，在浏览器中实现一直是个神话。

通过简单扫一下这个[demo](https://codepen.io/yuanchuan/pen/f70a1f9435dc90197b253b26b4d69d42)里面的代码，我们可以现象，逼真而又独特的云朵是可以通过使用`css`的`box-shadow`和一个包含两个元素的SVG过滤器`<filter>`去实现。

我们想要的仿真效果是通过`feTurbulence`和`feDisplacementMap`之间的微妙混合来实现的。SVG过滤器功能强大、复杂，并且提供了令人非常兴奋的功能（还包括[奥斯卡获奖算法](https://mrl.nyu.edu/~perlin/doc/oscar.html)）。然而，在它的底层，它们的复杂性可能有点吓人！
> 译者：奥斯卡获奖算法，这么牛逼？无知限制了我的想象。

虽然SVG的物理特性超出了本文的范畴，但是在[MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter)和[w3.org](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter)上有大量的文档。一个免费的关于`feTurbulence`和`feDisplacement`非常[有用的页面](https://oreillymedia.github.io/Using_SVG/extras/ch16-feTurbulence.html)（同时被作为这本[惊奇的书](http://shop.oreilly.com/product/0636920037972.do)的一个章节）

对于本文，我们专注学习如何使用SVG的过滤器实现惊人的效果。我们不需要深入研究其底层的算法，正如艺术家不需要了解涂漆的分子结构也能绘出令人惊叹的风景一样。

## 先从一些基础开始
CSS的`box-shadow`属性有五个值需要搞懂：
```CSS
box-shadow: <offsetX> <offsetY> <blurRadius> <spreadRadius> <color>;
```

让我们把这些值调高（可能比任何理智的开发人员调得都要高）：
```CSS
#cloud-square {
  background: turquoise;
  box-shadow: 200px 200px 50px 0px #000;
  width: 180px;
  height: 180px;
}

#cloud-circle {
  background: coral;
  border-radius: 50%;
  box-shadow: 200px 200px 50px 0px #000;
  width: 180px;
  height: 180px;
}
```
会得到下面的效果图：
![image](https://user-images.githubusercontent.com/26505680/60157291-fd721b80-9820-11e9-90d4-abe7a11e6275.png)

你曾经应该也玩过或者看过影子木偶对吗？像下面这样：
![image](https://user-images.githubusercontent.com/26505680/60157302-04992980-9821-11e9-8d32-81476d67ae02.png)
> 译者：看见这个，想起小时候自己也玩过， 两个拇指叉在一块能摆出鸽子的投影。

就像一只手改变形状可以改变投影一样，我们改变HTML的“源形状”也可以使渲染在浏览器中的投影变形。`box-shadow`复制了原始尺寸和`border-radius`上的“渐变”特性，SVG过滤器则同时应用于元素及其阴影。
```html
<svg width="0" height="0"> 
  <filter id="filter">
    <feTurbulence type="fractalNoise" baseFrequency=".01" numOctaves="10" />
    <feDisplacementMap in="SourceGraphic" scale="10" />
  </filter>
</svg>
```
这是我们目前的SVG代码，它不会被渲染，因为我们还没有定义任何可见的东西。它唯一的目的就是保存我们为`SourceGraphic`（也就是我们的`<div>`）提供的过滤器。

我们借助SVG过滤器的`ID`，通过添加CSS规则将HTML元素（`#cloud-circle`）和SVG过滤器进行关联：
```CSS
#cloud-circle {
  filter: url(#filter);
  box-shadow: 200px 200px 50px 0px #fff;
}
```
## 嗯！很棒，就是这样
![image](https://user-images.githubusercontent.com/26505680/60157321-111d8200-9821-11e9-94b7-4231e58e1a6c.png)
<font color="#A5A5A5">_在线查看[demo](https://codepen.io/beauhaus/pen/3699f7f8758c6af109b9f88b560f9439)_</font>

别急！我们只是了解了皮毛，还有很多好东西要看。

## 尝试使用feDisplacementMap的scale属性
使用这一属性进行一些非科学试验可以产生显著的效果。现在，我们保持`feTurbulence`的值不变，简单调整`feDisplacementMap`的`scale`属性值。

随着`scale`的增加（以30为增量），我们的源`<div>`变得扭曲，投射的阴影反应出天空中云出现的随机形式。
```html
<feDisplacementMap in="SourceGraphic" scale="180"/>
```
![image](https://user-images.githubusercontent.com/26505680/60157353-22668e80-9821-11e9-8b69-1dae5c0ddabc.png)
<font color="#A5A5A5">_在线查看[demo](https://codepen.io/beauhaus/pen/9454347106b6e7f46e11b7d8dca76ba7)_</font>

好了，我们有进展了！让我们稍微改变颜色，以形成更具说服力的云。
```CSS
body {
  background: linear-gradient(165deg, #527785 0%, #7FB4C7 100%);
}

#cloud-circle {
    width: 180px;
    height: 180px;
    background: #000;
    border-radius: 50%;
    filter: url(#filter);
    box-shadow: 200px 200px 50px 0px #fff;
}
```
现在，我们越来越接近真实的云朵效果了！
![image](https://user-images.githubusercontent.com/26505680/60157370-2e525080-9821-11e9-831f-220e0ae22c6c.png)

## 修改box-shadow的模糊度
下面一套图片展示了`box-shadow`属性的模糊度作用的效果，这里，我们以10px递增模糊值：
![image](https://user-images.githubusercontent.com/26505680/60157396-36aa8b80-9821-11e9-9367-fb568b2b5096.png)
<font color="#A5A5A5">_随着模糊值增加，云朵也变得更加柔和。_</font>

为了增加一点积云的效果，我们可以稍微扩宽源`<div>`的宽度：
```CSS
#cloud-circle {
  width: 500px; 
  height: 275px;
  background: #000;
  border-radius: 50%;
  filter: url(#filter);
  box-shadow: 200px 200px 60px 0px #fff;
}
```
![image](https://user-images.githubusercontent.com/26505680/60157408-41fdb700-9821-11e9-80d5-87e39ea363d5.png)
<font color="#A5A5A5">_很好，我们的源元素开始碍事了_</font>😫

等等，我们扩宽了源元素的宽度，但它现在遮挡在我们云层（白色阴影）的上方。让我们在更远的位置重新投影，这样我们的云就不会再被源图像遮挡了（你可以想象成把你的手往远离墙的方向移动，这样它就不会挡住你的影子木偶的视线了）。

这点我们通过CSS定位可以很好地实现。`<body>`是父元素，默认是静态定位的，我们给源`<div>`添加绝对定位。最初地，这也会重新定位我们的阴影，因此我们还需要增加阴影和元素之间的距离。
```CSS
#cloud-circle {
  width: 500px;
  height: 275px;
  background: #000;
  border-radius: 50%;
  filter: url(#filter);
  box-shadow: 400px 400px 60px 0px #fff; /* 增加投影位移 */
  position: absolute;
  top: -320px;
  left: -320px;
}
```
是的，我们已经实现了一个极具说服力的云：[这里查看](https://codepen.io/beauhaus/pen/315327cfbb84e1fca1057d851dec8fde)
![image](https://user-images.githubusercontent.com/26505680/60157435-52ae2d00-9821-11e9-99aa-301e7fa4da4c.png)
浏览器上展示的已经是一个相当完美的云了，但我不确定......这片云真的能公正地描述云女神涅斐勒吗？我相信我们还可以做得更好！
## 通过层次传达深度
这是我们想要的效果：
![image](https://user-images.githubusercontent.com/26505680/60157455-5d68c200-9821-11e9-87fa-238892c6cb4c.png)

从这张照片中云层的深度、纹理和丰富性来看，宙斯一定是读过艺术专业的。至少，他一定读过《通用设计法则》，这本书阐述了一个强大而又普通的概念：
> 照明偏差在深度和自然度的解释中起着重要作用，设计师可以通过多种方式操纵照明偏差，利用明暗区域之间的对比度来改变深度的外观。

这段话给了我们一个提示，我们可以将不同形状、大小和颜色的图层堆叠在一起，可以实现像参考图片中那样具有高保真度的云。我们要做的也只是多次调用SVG过滤器。
![image](https://user-images.githubusercontent.com/26505680/60157460-63f73980-9821-11e9-9f1d-04571847bc34.png)

使用三个SVG过滤器绘制前中后三朵云：
```html
<svg width="0" height="0">
    <!-- 后层 -->
    <filter id="filter-back">
      <feTurbulence type="fractalNoise" baseFrequency="0.012" numOctaves="4" />
      <feDisplacementMap  in="SourceGraphic" scale="170" />
    </filter>
    <!-- 中层 -->
    <filter id="filter-mid">
      <feTurbulence type="fractalNoise" baseFrequency="0.012" numOctaves="2" />
      <feDisplacementMap  in="SourceGraphic" scale="150" />
    </filter>
    <!-- 前层 -->
    <filter id="filter-front">
      <feTurbulence type="fractalNoise" baseFrequency="0.012" numOctaves="2" />
      <feDisplacementMap  in="SourceGraphic" scale="100" />
    </filter>
</svg>
```
通过分层的应用，我们有机会去探索`feTurbulence`并认识它的多样性。我们选择了较为平滑的类型：`fractalNoise`，对于`numOctaves`的值最高只调到了6。
<feTurbulence type="fractalNoise" baseFrequency="n" numOctaves="6"/>

上面这些意味着什么？我们来看一下`baseFrequency`这个属性，下面几张图片是不同`baseFrequency`值下的效果：
![image](https://user-images.githubusercontent.com/26505680/60157504-7b362700-9821-11e9-8b8c-9343d81edc4e.png)
<font color="#A5A5A5">_值越低，图像就越圆，越模糊。_</font>

从效果看，介于0.005~0.01的值比较符合我们想要的积云效果。

## 用numOctaves添加细节
增加`numOctaves`值允许我们以更细的粒度去渲染图像，这个过程需要大量的计算，因此需要注意：高值会严重影响性能。
![image](https://user-images.githubusercontent.com/26505680/60157531-88ebac80-9821-11e9-9112-e0340b88d2c2.png)
<font color="#A5A5A5">_numOctaves的值设置得越高，云的效果就越精细。_</font>

幸运的是我们不需要为达到精细的效果而设置太高的值，介于4~5就够了。
## 最后的效果
[查看效果](https://codepen.io/beauhaus/pen/QJrpPY)
![image](https://user-images.githubusercontent.com/26505680/60157554-96089b80-9821-11e9-80ff-378675470628.png)

## 用seed属性进行无限变形
关于`seed`属性有很多可以说，但就我们的目的而言，`seed`的作用可以归结为：<font color="5A78EA">**不同的值，不同的形状**</font>。

<font color="5A78EA">**柏林噪音函数**</font>使用这个值作为其随机数生成器的起点。选择不包含此属性则将`seed`值默认为0；当包含时，无论我们设置何值，都不需要担心会影响性能。

![](https://user-gold-cdn.xitu.io/2019/6/25/16b8df2ba4efea31?w=480&h=270&f=gif&s=4990813)
<font color="#A5A5A5">_不同的`seed`值，对应生成不同的形状。_</font>

上面的GIF代表了`seed`作用的效果。请记住，每个云都是分层的复合云（虽然我调整了每一层的属性，但我保持了它们的`seed`值一致）。
![image](https://user-images.githubusercontent.com/26505680/60157575-a4ef4e00-9821-11e9-9c97-e4c2f792493d.png)

仔细观察上面这张参考图片，我将3个云层`<div>`堆砌在一个基础的`div`上，通过反复试验不同的`seed`值，最终得到了与图中比较相似的形状。如下图：
![image](https://user-images.githubusercontent.com/26505680/60157582-acaef280-9821-11e9-98a0-233d8fa85d2a.png)
<font color="#A5A5A5">_在线查看[demo](https://codepen.io/beauhaus/pen/pmMaWV)_</font>

## 天空的极限
显然，认为我们用`<div>`在浏览器上绘制的云比涅斐勒高级是很荒谬的。

但是，我们能够梳理出CSS和SVG过滤器的神秘感越多，我们就越有能力去创造在视觉上令人惊叹的东西，并且高度保真于雷神的创作。那么，我们可以做进一步的试验了！
- [反射雾](https://codepen.io/beauhaus/pen/dELPLp/)
- [高层云](https://codepen.io/beauhaus/pen/OaevPr?editors=1100)

在这篇文章中，我们刚刚涉足了一个充满力量和复杂性的知识海洋，SVG过滤器通常看起来复杂地难以理解。

不过，就像[A Single Div Project](https://css-tricks.com/why-would-you-do-that-in-css/)和[Smith's绘画技术](https://css-tricks.com/solving-lifes-problems-with-css/)中的例子一样，有趣和实验性的方法总会给人惊艳的效果。

我希望这篇文章能让你对web上进行摄影写实开发感到兴奋，欢迎下方评论交流你的想法～
